### ISSUE TITLE
Email Template error when building the terraform template

### ISSUE THREAD

**Issue by jayanthv86** [oktadeveloper/okta-dac#1]
When I build the dac project on my Okta tenant jay.okta.com, I am getting this error on the terraform - 

```
Error: The API returned an error: You do not have permission to perform the requested action
 on main.tf line 195, in resource "okta_template_email" "email-welcome":
 195: resource "okta_template_email" "email-welcome" {
```

The reason being my tenant doesn't have permissions to edit the email template, and there are no APIs for this either.

**Comment by zeekhoo** [comment]
The email templates have to be manually updated now as of the latest terraform version (v0.13.x), Provider oktadeveloper/okta does not support it.

**Comment by zeekhoo** [comment]
Closing
