### ISSUE TITLE
Internal server error from Okta during `make all`

### ISSUE THREAD

**Issue by mdorn** [oktadeveloper/okta-dac#2]
I got the following error when following README instructions down to `make all`: 

```
Error: The API returned an error: Internal Server Error

  on main.tf line 181, in resource "okta_auth_server_policy_rule" "okta-dac-catch-all":
 181: resource "okta_auth_server_policy_rule" "okta-dac-catch-all" {

make: *** [okta] Error 1
```

I added `-parallelism=1` to the `terraform apply` command in the `planOkta` and that seemed to help.

**Comment by zeekhoo** [comment]
Added `-parallelism=1` to the Makefile command as suggested.
