### ISSUE TITLE
Update HCL scripts for Terraform v0.13.x

### ISSUE THREAD

**Issue by noinarisak** [oktadeveloper/okta-dac#3]
The HCL scripts located in `/terraform` authored against v0.12.x. The latest version v0.13 has explicitly new HCL provider code block that must be used. 

- Update the documentation to explicitly say what version terraform to use.
- Update the `main.tf` or add `verison.tf` to /terraform.

Workaround:

```bash
$ terraform 0.13upgrade .  
```

⚠️  Don't forget the `"."` in the command above.

**Comment by zeekhoo** [comment]
main.tf updated.
