### ISSUE TITLE
Missing o4o token when inCognito 

### ISSUE THREAD

**Issue by mattbaileyOkta** [oktadeveloper/okta-dac#9]
Missing o4o token when inCognito (Chrome)

Can't create users without the o4o token, tenants are spun up correctly.

Works fine when not in inCognito and o4o token is present in local storage.

**Comment by zeekhoo** [comment]
okta-dac has been tested to work in incognito on multiple browsers. There should be nothing that we could have done from a software design and implementation that makes incognito mode behave differently. Check your incognito mode settings: Likely, 3rd party cookies are enabled or some other setting has a higher level of privacy.

**Comment by mattbaileyOkta** [comment]
thanks Zee that was it! Cookies was disabled for inCognito.

**Comment by andymarch** [comment]
@zeekhoo looks like this is the default on Chrome when in incognito as of 83. Maybe we should warn if this cookie is not available?

**Comment by zeekhoo** [comment]
A-ha. We can surely add a blurb at the top of the README. Feel free to PR one ;). Or I can do it at some point.
